# Generated by Django 5.1.1 on 2024-11-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TProveedores',
            fields=[
                ('proveedorid', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('fecharegistro', models.DateField()),
                ('productosuministro', models.CharField(max_length=100)),
            ],
        ),
    ]
