# Generated by Django 5.1.1 on 2024-11-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TProveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TProveedores',
            new_name='TProveedor',
        ),
    ]
