# Generated by Django 5.1 on 2024-11-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TProveedores_app', '0002_rename_tproveedores_tproveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tproveedor',
            options={'verbose_name_plural': 'TProveedores'},
        ),
    ]
