# Generated by Django 5.1 on 2024-11-28 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TProductos_app', '0002_rename_tproductos_tproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TInventario',
            fields=[
                ('inventarioid', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidadinicial', models.IntegerField()),
                ('cantidadactual', models.IntegerField()),
                ('fechaactualizacion', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('notas', models.TextField()),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TProductos_app.tproducto')),
            ],
        ),
    ]
