# Generated by Django 5.1.1 on 2024-11-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TProductos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TProductos',
            new_name='TProducto',
        ),
    ]
